branches:
  only:
  - master
  - /^v[\d.]+$/
language: julia
julia:
  - 1.0
  - 1.4
codecov: true
after_success:
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
