name = "GpABC"
uuid = "e850a1a4-d859-11e8-3d54-a195e6d045d3"
authors = ["Evgeny Tankhilevich <et517@ic.ac.uk>"]
version = "0.1.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

# [compat]
# Colors = "0.9, 0.10, 0.11, 0.12"
# Distances = "0.8, 0.9"
# Distributions = "0.21, 0.22, 0.23"
# ForwardDiff = "0.10"
# KernelDensity = "0.5"
# Optim = "0.19.4, 0.20, 0.21, 0.22"
# OrdinaryDiffEq = "5.23"
# PlotUtils = "1.0.5"
# RecipesBase = "0.8, 1.0.1"
# StatsBase = "0.32, 0.33"
# julia = "1.0.2"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles", "Random", "Statistics"]
